name: Discord Notification

on: [push]

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Discord message
        uses: Ilshidur/action-discord@latest
        with:
          args: >
            {
              "username": "GitHub Actions",
              "content": "A new commit has been pushed to ${{ github.repository }}.\nCommit: ${{ github.sha }}\nMessage: ${{ github.event.head_commit.message }}\nAuthor: ${{ github.event.head_commit.author.name }}\nURL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
            }
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}