name: Discord Notification

on: [push]

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Discord message
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            A new commit has been pushed to ${{ github.repository }}.
            Commit: ${{ github.sha }}
            Message: ${{ github.event.head_commit.message }}
            Author: ${{ github.event.head_commit.author.name }}
            URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          username: 'GitHub Actions'
