name: Discord Notification

on: [push]

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: 'New update in ${{ github.repository }}'
          embed-description: 'Author: ${{ github.event.head_commit.author.username }}'
          embed-color: 3447003 # This is the color blue in decimal
          embed-footer-text: ${{ github.event.head_commit.message}}
          embed-author-name: ${{ github.event.head_commit.author.username }}
          embed-author-icon-url: ${{ github.event.head_commit.author.avatar_url }}