name: Discord Notification

on: [push]

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: 'New commit in ${{ github.repository }}'
          embed-description: |
            Commit: ${{ github.sha }}
            Message: ${{ github.event.head_commit.message }}
            Author: ${{ github.event.head_commit.author.name }}
          embed-url: 'https://github.com/${{ github.repository }}/commit/${{ github.sha }}'
          embed-color: 16711680 # This is the color red in decimal
          embed-footer-text: 'GitHub Actions'
